name: Construir Documento LaTeX

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_latex:
    name: Compilar PDF desde LaTeX
    runs-on: rocky
    permissions:
      contents: write

    steps:
      - name: Cloning Repo
        uses: actions/checkout@v4

      - name: Compiling LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          
      - name: Release PDF
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: "v1.0.${{ github.run_number }}"
          name: "resume-DM-v1.0.${{ github.run_number }}"
          files: main.pdf
