name: Construir Documento LaTeX

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_latex:
    name: Compilar PDF desde LaTeX
    runs-on: rocky

    steps:
      - name: Cloning Repo
        uses: actions/checkout@v4

      - name: Compiling LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          
      - name: Pushing PDF
        uses: actions/upload-artifact@v4
        with:
          name: DM_resume
          path: main.pdf
